const path = require("node:path");
const tsPlugin = require("@typescript-eslint/eslint-plugin");
const tsParser = require("@typescript-eslint/parser");
const promise = require("eslint-plugin-promise");
const reactRefreshModule = require("eslint-plugin-react-refresh");
const unicornModule = require("eslint-plugin-unicorn");
const vitest = require("@vitest/eslint-plugin");

const reactRefresh = reactRefreshModule.default ?? reactRefreshModule;
const unicorn = unicornModule.default ?? unicornModule;

const typescriptFiles = ["**/*.ts", "**/*.tsx"];
const testFiles = ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx"];

const rulesAt = (severity, ruleNames) => Object.fromEntries(ruleNames.map((ruleName) => [ruleName, severity]));
const pluginRulesAt = (pluginName, severity, ruleNames) =>
  rulesAt(
    severity,
    ruleNames.map((ruleName) => `${pluginName}/${ruleName}`),
  );

const baseRules = {
  ...rulesAt("error", [
    "array-callback-return",
    "capitalized-comments",
    "complexity",
    "curly",
    "default-case-last",
    "default-param-last",
    "eqeqeq",
    "max-lines-per-function",
    "no-alert",
    "no-continue",
    "no-duplicate-imports",
    "no-else-return",
    "no-empty",
    "no-fallthrough",
    "no-implicit-coercion",
    "no-inner-declarations",
    "no-inline-comments",
    "no-lone-blocks",
    "no-lonely-if",
    "no-loop-func",
    "no-multi-str",
    "no-negated-condition",
    "no-nested-ternary",
    "no-param-reassign",
    "no-return-assign",
    "no-sequences",
    "no-self-compare",
    "no-shadow",
    "no-template-curly-in-string",
    "no-undef",
    "no-undefined",
    "no-unmodified-loop-condition",
    "no-unneeded-ternary",
    "no-use-before-define",
    "no-useless-concat",
    "no-useless-constructor",
    "no-useless-return",
    "no-void",
    "object-shorthand",
    "prefer-const",
    "prefer-object-has-own",
    "prefer-template",
    "sort-keys",
    "yoda",
  ]),
  ...pluginRulesAt("@typescript-eslint", "error", [
    "ban-tslint-comment",
    "consistent-generic-constructors",
    "consistent-type-assertions",
    "consistent-type-imports",
    "explicit-function-return-type",
    "explicit-module-boundary-types",
    "no-confusing-non-null-assertion",
    "no-dynamic-delete",
    "no-empty-object-type",
    "no-explicit-any",
    "no-import-type-side-effects",
    "no-invalid-void-type",
    "no-misused-promises",
    "no-namespace",
    "no-non-null-asserted-nullish-coalescing",
    "no-non-null-assertion",
    "no-require-imports",
    "no-unnecessary-type-assertion",
    "no-unnecessary-type-constraint",
    "no-unsafe-function-type",
    "no-var-requires",
    "only-throw-error",
    "prefer-find",
    "prefer-for-of",
    "prefer-function-type",
    "prefer-includes",
    "prefer-nullish-coalescing",
    "prefer-readonly",
    "prefer-ts-expect-error",
    "require-await",
    "restrict-plus-operands",
    "switch-exhaustiveness-check",
  ]),
  ...pluginRulesAt("promise", "error", [
    "always-return",
    "avoid-new",
    "catch-or-return",
    "no-multiple-resolved",
    "no-new-statics",
    "no-promise-in-callback",
    "no-return-in-finally",
    "no-return-wrap",
    "param-names",
    "prefer-catch",
    "valid-params",
  ]),
  ...pluginRulesAt("react-refresh", "error", ["only-export-components"]),
  ...pluginRulesAt("unicorn", "error", [
    "consistent-assert",
    "consistent-date-clone",
    "consistent-existence-index-check",
    "empty-brace-spaces",
    "escape-case",
    "explicit-length-check",
    "no-await-in-promise-methods",
    "no-unnecessary-await",
    "no-unreadable-iife",
    "no-useless-fallback-in-spread",
    "no-useless-length-check",
    "no-useless-promise-resolve-reject",
    "no-useless-switch-case",
    "no-useless-undefined",
    "no-zero-fractions",
    "prefer-array-flat-map",
    "prefer-array-index-of",
    "prefer-array-some",
    "prefer-at",
    "prefer-bigint-literals",
    "prefer-classlist-toggle",
    "prefer-date-now",
    "prefer-dom-node-append",
    "prefer-dom-node-dataset",
    "prefer-dom-node-remove",
    "prefer-dom-node-text-content",
    "prefer-keyboard-event-key",
    "prefer-math-min-max",
    "prefer-optional-catch-binding",
    "prefer-regexp-test",
    "prefer-set-size",
    "prefer-spread",
    "prefer-string-raw",
    "prefer-string-replace-all",
    "prefer-string-slice",
    "prefer-string-starts-ends-with",
    "prefer-string-trim-start-end",
    "prefer-type-error",
    "require-array-join-separator",
    "require-number-to-fixed-digits-argument",
    "switch-case-braces",
    "text-encoding-identifier-case",
    "throw-new-error",
  ]),
  "@typescript-eslint/array-type": ["error", { default: "array-simple" }],
  "@typescript-eslint/consistent-type-definitions": ["error", "type"],
  "func-style": ["error", "expression"],
  "no-console": "warn",
  "no-restricted-exports": ["error", { restrictedNamedExports: ["default"] }],
  "unicorn/filename-case": ["error", { case: "kebabCase" }],
};

const testRules = pluginRulesAt("vitest", "error", [
  "expect-expect",
  "hoisted-apis-on-top",
  "no-commented-out-tests",
  "no-conditional-expect",
  "no-conditional-tests",
  "no-disabled-tests",
  "no-focused-tests",
  "no-identical-title",
  "no-import-node-test",
  "no-standalone-expect",
  "require-awaited-expect-poll",
  "require-local-test-context-for-concurrent-snapshots",
  "require-mock-type-parameters",
  "require-to-throw-message",
  "valid-describe-callback",
  "valid-expect",
  "valid-expect-in-promise",
  "valid-title",
  "warn-todo",
]);

module.exports = [
  { ignores: ["dist/**", "node_modules/**"] },
  {
    files: typescriptFiles,
    languageOptions: {
      globals: { Preferences: "readonly" },
      parser: tsParser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: path.join(__dirname, ".."),
      },
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
      promise,
      "react-refresh": reactRefresh,
      unicorn,
      vitest,
    },
    rules: baseRules,
  },
  { files: ["src/search-term.tsx"], rules: { "no-restricted-exports": "off" } },
  { files: ["src/App.tsx"], rules: { "unicorn/filename-case": "off" } },
  {
    files: ["src/components/ui/**/*.tsx", "src/lib/utils.ts"],
    rules: {
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "func-style": "off",
      "sort-keys": "off",
    },
  },
  {
    files: ["src/components/ui/**/*.tsx"],
    rules: { "react-refresh/only-export-components": "off" },
  },
  { files: testFiles, rules: testRules },
];
